/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ProduceRouteImport } from './routes/produce'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminArticleIdRouteImport } from './routes/_authenticated/admin/$articleId'
import { Route as ApiPublicNewsImageSplatRouteImport } from './routes/api/public/news-image/$'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduceRoute = ProduceRouteImport.update({
  id: '/produce',
  path: '/produce',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminArticleIdRoute =
  AuthenticatedAdminArticleIdRouteImport.update({
    id: '/admin/$articleId',
    path: '/admin/$articleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNewsImageSplatRoute = ApiPublicNewsImageSplatRouteImport.update({
  id: '/api/public/news-image/$',
  path: '/api/public/news-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/funding': typeof FundingRoute
  '/news': typeof NewsRoute
  '/operations': typeof OperationsRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/produce': typeof ProduceRoute
  '/project': typeof ProjectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/why-us': typeof WhyUsRoute
  '/admin/$articleId': typeof AuthenticatedAdminArticleIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/news-image/$': typeof ApiPublicNewsImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/funding': typeof FundingRoute
  '/news': typeof NewsRoute
  '/operations': typeof OperationsRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/produce': typeof ProduceRoute
  '/project': typeof ProjectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/why-us': typeof WhyUsRoute
  '/admin/$articleId': typeof AuthenticatedAdminArticleIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/news-image/$': typeof ApiPublicNewsImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/funding': typeof FundingRoute
  '/news': typeof NewsRoute
  '/operations': typeof OperationsRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/produce': typeof ProduceRoute
  '/project': typeof ProjectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/why-us': typeof WhyUsRoute
  '/_authenticated/admin/$articleId': typeof AuthenticatedAdminArticleIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/news-image/$': typeof ApiPublicNewsImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/funding'
    | '/news'
    | '/operations'
    | '/partnerships'
    | '/privacy'
    | '/produce'
    | '/project'
    | '/sitemap.xml'
    | '/sustainability'
    | '/terms'
    | '/why-us'
    | '/admin/$articleId'
    | '/admin/'
    | '/api/public/news-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/funding'
    | '/news'
    | '/operations'
    | '/partnerships'
    | '/privacy'
    | '/produce'
    | '/project'
    | '/sitemap.xml'
    | '/sustainability'
    | '/terms'
    | '/why-us'
    | '/admin/$articleId'
    | '/admin'
    | '/api/public/news-image/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/funding'
    | '/news'
    | '/operations'
    | '/partnerships'
    | '/privacy'
    | '/produce'
    | '/project'
    | '/sitemap.xml'
    | '/sustainability'
    | '/terms'
    | '/why-us'
    | '/_authenticated/admin/$articleId'
    | '/_authenticated/admin/'
    | '/api/public/news-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FundingRoute: typeof FundingRoute
  NewsRoute: typeof NewsRoute
  OperationsRoute: typeof OperationsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProduceRoute: typeof ProduceRoute
  ProjectRoute: typeof ProjectRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  WhyUsRoute: typeof WhyUsRoute
  ApiPublicNewsImageSplatRoute: typeof ApiPublicNewsImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produce': {
      id: '/produce'
      path: '/produce'
      fullPath: '/produce'
      preLoaderRoute: typeof ProduceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$articleId': {
      id: '/_authenticated/admin/$articleId'
      path: '/admin/$articleId'
      fullPath: '/admin/$articleId'
      preLoaderRoute: typeof AuthenticatedAdminArticleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/news-image/$': {
      id: '/api/public/news-image/$'
      path: '/api/public/news-image/$'
      fullPath: '/api/public/news-image/$'
      preLoaderRoute: typeof ApiPublicNewsImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminArticleIdRoute: typeof AuthenticatedAdminArticleIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminArticleIdRoute: AuthenticatedAdminArticleIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FundingRoute: FundingRoute,
  NewsRoute: NewsRoute,
  OperationsRoute: OperationsRoute,
  PartnershipsRoute: PartnershipsRoute,
  PrivacyRoute: PrivacyRoute,
  ProduceRoute: ProduceRoute,
  ProjectRoute: ProjectRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  WhyUsRoute: WhyUsRoute,
  ApiPublicNewsImageSplatRoute: ApiPublicNewsImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
